// Copyright 2020. The Tari Project
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
// following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
// disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
// following disclaimer in the documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
// products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: base_node.proto

package tari_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseNode_ListHeaders_FullMethodName                          = "/tari.rpc.BaseNode/ListHeaders"
	BaseNode_GetHeaderByHash_FullMethodName                      = "/tari.rpc.BaseNode/GetHeaderByHash"
	BaseNode_GetBlocks_FullMethodName                            = "/tari.rpc.BaseNode/GetBlocks"
	BaseNode_GetBlockTiming_FullMethodName                       = "/tari.rpc.BaseNode/GetBlockTiming"
	BaseNode_GetConstants_FullMethodName                         = "/tari.rpc.BaseNode/GetConstants"
	BaseNode_GetBlockSize_FullMethodName                         = "/tari.rpc.BaseNode/GetBlockSize"
	BaseNode_GetBlockFees_FullMethodName                         = "/tari.rpc.BaseNode/GetBlockFees"
	BaseNode_GetVersion_FullMethodName                           = "/tari.rpc.BaseNode/GetVersion"
	BaseNode_CheckForUpdates_FullMethodName                      = "/tari.rpc.BaseNode/CheckForUpdates"
	BaseNode_GetTokensInCirculation_FullMethodName               = "/tari.rpc.BaseNode/GetTokensInCirculation"
	BaseNode_GetNetworkDifficulty_FullMethodName                 = "/tari.rpc.BaseNode/GetNetworkDifficulty"
	BaseNode_GetNewBlockTemplate_FullMethodName                  = "/tari.rpc.BaseNode/GetNewBlockTemplate"
	BaseNode_GetNewBlock_FullMethodName                          = "/tari.rpc.BaseNode/GetNewBlock"
	BaseNode_GetNewBlockWithCoinbases_FullMethodName             = "/tari.rpc.BaseNode/GetNewBlockWithCoinbases"
	BaseNode_GetNewBlockTemplateWithCoinbases_FullMethodName     = "/tari.rpc.BaseNode/GetNewBlockTemplateWithCoinbases"
	BaseNode_GetNewBlockBlob_FullMethodName                      = "/tari.rpc.BaseNode/GetNewBlockBlob"
	BaseNode_SubmitBlock_FullMethodName                          = "/tari.rpc.BaseNode/SubmitBlock"
	BaseNode_SubmitBlockBlob_FullMethodName                      = "/tari.rpc.BaseNode/SubmitBlockBlob"
	BaseNode_SubmitTransaction_FullMethodName                    = "/tari.rpc.BaseNode/SubmitTransaction"
	BaseNode_GetSyncInfo_FullMethodName                          = "/tari.rpc.BaseNode/GetSyncInfo"
	BaseNode_GetSyncProgress_FullMethodName                      = "/tari.rpc.BaseNode/GetSyncProgress"
	BaseNode_GetTipInfo_FullMethodName                           = "/tari.rpc.BaseNode/GetTipInfo"
	BaseNode_SearchKernels_FullMethodName                        = "/tari.rpc.BaseNode/SearchKernels"
	BaseNode_SearchUtxos_FullMethodName                          = "/tari.rpc.BaseNode/SearchUtxos"
	BaseNode_FetchMatchingUtxos_FullMethodName                   = "/tari.rpc.BaseNode/FetchMatchingUtxos"
	BaseNode_GetPeers_FullMethodName                             = "/tari.rpc.BaseNode/GetPeers"
	BaseNode_GetMempoolTransactions_FullMethodName               = "/tari.rpc.BaseNode/GetMempoolTransactions"
	BaseNode_TransactionState_FullMethodName                     = "/tari.rpc.BaseNode/TransactionState"
	BaseNode_Identify_FullMethodName                             = "/tari.rpc.BaseNode/Identify"
	BaseNode_GetNetworkStatus_FullMethodName                     = "/tari.rpc.BaseNode/GetNetworkStatus"
	BaseNode_ListConnectedPeers_FullMethodName                   = "/tari.rpc.BaseNode/ListConnectedPeers"
	BaseNode_GetMempoolStats_FullMethodName                      = "/tari.rpc.BaseNode/GetMempoolStats"
	BaseNode_GetActiveValidatorNodes_FullMethodName              = "/tari.rpc.BaseNode/GetActiveValidatorNodes"
	BaseNode_GetValidatorNodeChanges_FullMethodName              = "/tari.rpc.BaseNode/GetValidatorNodeChanges"
	BaseNode_GetShardKey_FullMethodName                          = "/tari.rpc.BaseNode/GetShardKey"
	BaseNode_GetTemplateRegistrations_FullMethodName             = "/tari.rpc.BaseNode/GetTemplateRegistrations"
	BaseNode_GetSideChainUtxos_FullMethodName                    = "/tari.rpc.BaseNode/GetSideChainUtxos"
	BaseNode_GetNetworkState_FullMethodName                      = "/tari.rpc.BaseNode/GetNetworkState"
	BaseNode_SearchPaymentReferences_FullMethodName              = "/tari.rpc.BaseNode/SearchPaymentReferences"
	BaseNode_SearchPaymentReferencesViaOutputHash_FullMethodName = "/tari.rpc.BaseNode/SearchPaymentReferencesViaOutputHash"
)

// BaseNodeClient is the client API for BaseNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC interface for interacting with the base node.
type BaseNodeClient interface {
	// Lists headers in the current best chain
	ListHeaders(ctx context.Context, in *ListHeadersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeaderResponse], error)
	// Get header by hash
	GetHeaderByHash(ctx context.Context, in *GetHeaderByHashRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error)
	// Returns blocks in the current best chain. Currently only supports querying by height
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error)
	// Returns the block timing for the chain heights
	GetBlockTiming(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*BlockTimingResponse, error)
	// Returns the network Constants
	GetConstants(ctx context.Context, in *BlockHeight, opts ...grpc.CallOption) (*ConsensusConstants, error)
	// Returns Block Sizes
	GetBlockSize(ctx context.Context, in *BlockGroupRequest, opts ...grpc.CallOption) (*BlockGroupResponse, error)
	// Returns Block Fees
	GetBlockFees(ctx context.Context, in *BlockGroupRequest, opts ...grpc.CallOption) (*BlockGroupResponse, error)
	// Get Version
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseNodeGetVersionResponse, error)
	// Check for new updates
	CheckForUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SoftwareUpdate, error)
	// Get coins in circulation
	GetTokensInCirculation(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueAtHeightResponse], error)
	// Get network difficulties
	GetNetworkDifficulty(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkDifficultyResponse], error)
	// Get the block template
	GetNewBlockTemplate(ctx context.Context, in *NewBlockTemplateRequest, opts ...grpc.CallOption) (*NewBlockTemplateResponse, error)
	// Construct a new block from a provided template
	GetNewBlock(ctx context.Context, in *NewBlockTemplate, opts ...grpc.CallOption) (*GetNewBlockResult, error)
	// Construct a new block from a provided template
	GetNewBlockWithCoinbases(ctx context.Context, in *GetNewBlockWithCoinbasesRequest, opts ...grpc.CallOption) (*GetNewBlockResult, error)
	// Construct a new block from a provided template
	GetNewBlockTemplateWithCoinbases(ctx context.Context, in *GetNewBlockTemplateWithCoinbasesRequest, opts ...grpc.CallOption) (*GetNewBlockResult, error)
	// Construct a new block and header blob from a provided template
	GetNewBlockBlob(ctx context.Context, in *NewBlockTemplate, opts ...grpc.CallOption) (*GetNewBlockBlobResult, error)
	// Submit a new block for propagation
	SubmitBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	// Submit a new mined block blob for propagation
	SubmitBlockBlob(ctx context.Context, in *BlockBlobRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
	// Submit a transaction for propagation
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	// Get the base node sync information
	GetSyncInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncInfoResponse, error)
	// Get the base node sync information
	GetSyncProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncProgressResponse, error)
	// Get the base node tip information
	GetTipInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TipInfoResponse, error)
	// Search for blocks containing the specified kernels
	SearchKernels(ctx context.Context, in *SearchKernelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error)
	// Search for blocks containing the specified commitments
	SearchUtxos(ctx context.Context, in *SearchUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error)
	// Fetch any utxos that exist in the main chain
	FetchMatchingUtxos(ctx context.Context, in *FetchMatchingUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchMatchingUtxosResponse], error)
	// get all peers from the base node
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPeersResponse], error)
	GetMempoolTransactions(ctx context.Context, in *GetMempoolTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetMempoolTransactionsResponse], error)
	TransactionState(ctx context.Context, in *TransactionStateRequest, opts ...grpc.CallOption) (*TransactionStateResponse, error)
	// This returns the node's network identity
	Identify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIdentity, error)
	// Get Base Node network connectivity status
	GetNetworkStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkStatusResponse, error)
	// List currently connected peers
	ListConnectedPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListConnectedPeersResponse, error)
	// Get mempool stats
	GetMempoolStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MempoolStatsResponse, error)
	// Get VNs
	GetActiveValidatorNodes(ctx context.Context, in *GetActiveValidatorNodesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetActiveValidatorNodesResponse], error)
	GetValidatorNodeChanges(ctx context.Context, in *GetValidatorNodeChangesRequest, opts ...grpc.CallOption) (*GetValidatorNodeChangesResponse, error)
	GetShardKey(ctx context.Context, in *GetShardKeyRequest, opts ...grpc.CallOption) (*GetShardKeyResponse, error)
	// Get templates
	GetTemplateRegistrations(ctx context.Context, in *GetTemplateRegistrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTemplateRegistrationResponse], error)
	GetSideChainUtxos(ctx context.Context, in *GetSideChainUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSideChainUtxosResponse], error)
	GetNetworkState(ctx context.Context, in *GetNetworkStateRequest, opts ...grpc.CallOption) (*GetNetworkStateResponse, error)
	// PayRef (Payment Reference) lookup for block explorers and external services
	SearchPaymentReferences(ctx context.Context, in *SearchPaymentReferencesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentReferenceResponse], error)
	// PayRef (Payment Reference) lookup for block explorers and external services via output hash
	SearchPaymentReferencesViaOutputHash(ctx context.Context, in *FetchMatchingUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentReferenceResponse], error)
}

type baseNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseNodeClient(cc grpc.ClientConnInterface) BaseNodeClient {
	return &baseNodeClient{cc}
}

func (c *baseNodeClient) ListHeaders(ctx context.Context, in *ListHeadersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeaderResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[0], BaseNode_ListHeaders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListHeadersRequest, BlockHeaderResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_ListHeadersClient = grpc.ServerStreamingClient[BlockHeaderResponse]

func (c *baseNodeClient) GetHeaderByHash(ctx context.Context, in *GetHeaderByHashRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockHeaderResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetHeaderByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[1], BaseNode_GetBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBlocksRequest, HistoricalBlock]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetBlocksClient = grpc.ServerStreamingClient[HistoricalBlock]

func (c *baseNodeClient) GetBlockTiming(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*BlockTimingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockTimingResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetBlockTiming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetConstants(ctx context.Context, in *BlockHeight, opts ...grpc.CallOption) (*ConsensusConstants, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsensusConstants)
	err := c.cc.Invoke(ctx, BaseNode_GetConstants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetBlockSize(ctx context.Context, in *BlockGroupRequest, opts ...grpc.CallOption) (*BlockGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockGroupResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetBlockSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetBlockFees(ctx context.Context, in *BlockGroupRequest, opts ...grpc.CallOption) (*BlockGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockGroupResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetBlockFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseNodeGetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseNodeGetVersionResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) CheckForUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SoftwareUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftwareUpdate)
	err := c.cc.Invoke(ctx, BaseNode_CheckForUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetTokensInCirculation(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueAtHeightResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[2], BaseNode_GetTokensInCirculation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBlocksRequest, ValueAtHeightResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetTokensInCirculationClient = grpc.ServerStreamingClient[ValueAtHeightResponse]

func (c *baseNodeClient) GetNetworkDifficulty(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetworkDifficultyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[3], BaseNode_GetNetworkDifficulty_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeightRequest, NetworkDifficultyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetNetworkDifficultyClient = grpc.ServerStreamingClient[NetworkDifficultyResponse]

func (c *baseNodeClient) GetNewBlockTemplate(ctx context.Context, in *NewBlockTemplateRequest, opts ...grpc.CallOption) (*NewBlockTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewBlockTemplateResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetNewBlockTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetNewBlock(ctx context.Context, in *NewBlockTemplate, opts ...grpc.CallOption) (*GetNewBlockResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewBlockResult)
	err := c.cc.Invoke(ctx, BaseNode_GetNewBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetNewBlockWithCoinbases(ctx context.Context, in *GetNewBlockWithCoinbasesRequest, opts ...grpc.CallOption) (*GetNewBlockResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewBlockResult)
	err := c.cc.Invoke(ctx, BaseNode_GetNewBlockWithCoinbases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetNewBlockTemplateWithCoinbases(ctx context.Context, in *GetNewBlockTemplateWithCoinbasesRequest, opts ...grpc.CallOption) (*GetNewBlockResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewBlockResult)
	err := c.cc.Invoke(ctx, BaseNode_GetNewBlockTemplateWithCoinbases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetNewBlockBlob(ctx context.Context, in *NewBlockTemplate, opts ...grpc.CallOption) (*GetNewBlockBlobResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewBlockBlobResult)
	err := c.cc.Invoke(ctx, BaseNode_GetNewBlockBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) SubmitBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, BaseNode_SubmitBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) SubmitBlockBlob(ctx context.Context, in *BlockBlobRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, BaseNode_SubmitBlockBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, BaseNode_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetSyncInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncInfoResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetSyncInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetSyncProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProgressResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetSyncProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetTipInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TipInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TipInfoResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetTipInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) SearchKernels(ctx context.Context, in *SearchKernelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[4], BaseNode_SearchKernels_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchKernelsRequest, HistoricalBlock]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchKernelsClient = grpc.ServerStreamingClient[HistoricalBlock]

func (c *baseNodeClient) SearchUtxos(ctx context.Context, in *SearchUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HistoricalBlock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[5], BaseNode_SearchUtxos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchUtxosRequest, HistoricalBlock]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchUtxosClient = grpc.ServerStreamingClient[HistoricalBlock]

func (c *baseNodeClient) FetchMatchingUtxos(ctx context.Context, in *FetchMatchingUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchMatchingUtxosResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[6], BaseNode_FetchMatchingUtxos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchMatchingUtxosRequest, FetchMatchingUtxosResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_FetchMatchingUtxosClient = grpc.ServerStreamingClient[FetchMatchingUtxosResponse]

func (c *baseNodeClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPeersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[7], BaseNode_GetPeers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPeersRequest, GetPeersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetPeersClient = grpc.ServerStreamingClient[GetPeersResponse]

func (c *baseNodeClient) GetMempoolTransactions(ctx context.Context, in *GetMempoolTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetMempoolTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[8], BaseNode_GetMempoolTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMempoolTransactionsRequest, GetMempoolTransactionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetMempoolTransactionsClient = grpc.ServerStreamingClient[GetMempoolTransactionsResponse]

func (c *baseNodeClient) TransactionState(ctx context.Context, in *TransactionStateRequest, opts ...grpc.CallOption) (*TransactionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionStateResponse)
	err := c.cc.Invoke(ctx, BaseNode_TransactionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) Identify(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIdentity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeIdentity)
	err := c.cc.Invoke(ctx, BaseNode_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetNetworkStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStatusResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetNetworkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) ListConnectedPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListConnectedPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectedPeersResponse)
	err := c.cc.Invoke(ctx, BaseNode_ListConnectedPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetMempoolStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MempoolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MempoolStatsResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetMempoolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetActiveValidatorNodes(ctx context.Context, in *GetActiveValidatorNodesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetActiveValidatorNodesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[9], BaseNode_GetActiveValidatorNodes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetActiveValidatorNodesRequest, GetActiveValidatorNodesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetActiveValidatorNodesClient = grpc.ServerStreamingClient[GetActiveValidatorNodesResponse]

func (c *baseNodeClient) GetValidatorNodeChanges(ctx context.Context, in *GetValidatorNodeChangesRequest, opts ...grpc.CallOption) (*GetValidatorNodeChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValidatorNodeChangesResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetValidatorNodeChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetShardKey(ctx context.Context, in *GetShardKeyRequest, opts ...grpc.CallOption) (*GetShardKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardKeyResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetShardKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) GetTemplateRegistrations(ctx context.Context, in *GetTemplateRegistrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTemplateRegistrationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[10], BaseNode_GetTemplateRegistrations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTemplateRegistrationsRequest, GetTemplateRegistrationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetTemplateRegistrationsClient = grpc.ServerStreamingClient[GetTemplateRegistrationResponse]

func (c *baseNodeClient) GetSideChainUtxos(ctx context.Context, in *GetSideChainUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSideChainUtxosResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[11], BaseNode_GetSideChainUtxos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSideChainUtxosRequest, GetSideChainUtxosResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetSideChainUtxosClient = grpc.ServerStreamingClient[GetSideChainUtxosResponse]

func (c *baseNodeClient) GetNetworkState(ctx context.Context, in *GetNetworkStateRequest, opts ...grpc.CallOption) (*GetNetworkStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkStateResponse)
	err := c.cc.Invoke(ctx, BaseNode_GetNetworkState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseNodeClient) SearchPaymentReferences(ctx context.Context, in *SearchPaymentReferencesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentReferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[12], BaseNode_SearchPaymentReferences_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchPaymentReferencesRequest, PaymentReferenceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchPaymentReferencesClient = grpc.ServerStreamingClient[PaymentReferenceResponse]

func (c *baseNodeClient) SearchPaymentReferencesViaOutputHash(ctx context.Context, in *FetchMatchingUtxosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentReferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BaseNode_ServiceDesc.Streams[13], BaseNode_SearchPaymentReferencesViaOutputHash_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchMatchingUtxosRequest, PaymentReferenceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchPaymentReferencesViaOutputHashClient = grpc.ServerStreamingClient[PaymentReferenceResponse]

// BaseNodeServer is the server API for BaseNode service.
// All implementations must embed UnimplementedBaseNodeServer
// for forward compatibility.
//
// The gRPC interface for interacting with the base node.
type BaseNodeServer interface {
	// Lists headers in the current best chain
	ListHeaders(*ListHeadersRequest, grpc.ServerStreamingServer[BlockHeaderResponse]) error
	// Get header by hash
	GetHeaderByHash(context.Context, *GetHeaderByHashRequest) (*BlockHeaderResponse, error)
	// Returns blocks in the current best chain. Currently only supports querying by height
	GetBlocks(*GetBlocksRequest, grpc.ServerStreamingServer[HistoricalBlock]) error
	// Returns the block timing for the chain heights
	GetBlockTiming(context.Context, *HeightRequest) (*BlockTimingResponse, error)
	// Returns the network Constants
	GetConstants(context.Context, *BlockHeight) (*ConsensusConstants, error)
	// Returns Block Sizes
	GetBlockSize(context.Context, *BlockGroupRequest) (*BlockGroupResponse, error)
	// Returns Block Fees
	GetBlockFees(context.Context, *BlockGroupRequest) (*BlockGroupResponse, error)
	// Get Version
	GetVersion(context.Context, *Empty) (*BaseNodeGetVersionResponse, error)
	// Check for new updates
	CheckForUpdates(context.Context, *Empty) (*SoftwareUpdate, error)
	// Get coins in circulation
	GetTokensInCirculation(*GetBlocksRequest, grpc.ServerStreamingServer[ValueAtHeightResponse]) error
	// Get network difficulties
	GetNetworkDifficulty(*HeightRequest, grpc.ServerStreamingServer[NetworkDifficultyResponse]) error
	// Get the block template
	GetNewBlockTemplate(context.Context, *NewBlockTemplateRequest) (*NewBlockTemplateResponse, error)
	// Construct a new block from a provided template
	GetNewBlock(context.Context, *NewBlockTemplate) (*GetNewBlockResult, error)
	// Construct a new block from a provided template
	GetNewBlockWithCoinbases(context.Context, *GetNewBlockWithCoinbasesRequest) (*GetNewBlockResult, error)
	// Construct a new block from a provided template
	GetNewBlockTemplateWithCoinbases(context.Context, *GetNewBlockTemplateWithCoinbasesRequest) (*GetNewBlockResult, error)
	// Construct a new block and header blob from a provided template
	GetNewBlockBlob(context.Context, *NewBlockTemplate) (*GetNewBlockBlobResult, error)
	// Submit a new block for propagation
	SubmitBlock(context.Context, *Block) (*SubmitBlockResponse, error)
	// Submit a new mined block blob for propagation
	SubmitBlockBlob(context.Context, *BlockBlobRequest) (*SubmitBlockResponse, error)
	// Submit a transaction for propagation
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	// Get the base node sync information
	GetSyncInfo(context.Context, *Empty) (*SyncInfoResponse, error)
	// Get the base node sync information
	GetSyncProgress(context.Context, *Empty) (*SyncProgressResponse, error)
	// Get the base node tip information
	GetTipInfo(context.Context, *Empty) (*TipInfoResponse, error)
	// Search for blocks containing the specified kernels
	SearchKernels(*SearchKernelsRequest, grpc.ServerStreamingServer[HistoricalBlock]) error
	// Search for blocks containing the specified commitments
	SearchUtxos(*SearchUtxosRequest, grpc.ServerStreamingServer[HistoricalBlock]) error
	// Fetch any utxos that exist in the main chain
	FetchMatchingUtxos(*FetchMatchingUtxosRequest, grpc.ServerStreamingServer[FetchMatchingUtxosResponse]) error
	// get all peers from the base node
	GetPeers(*GetPeersRequest, grpc.ServerStreamingServer[GetPeersResponse]) error
	GetMempoolTransactions(*GetMempoolTransactionsRequest, grpc.ServerStreamingServer[GetMempoolTransactionsResponse]) error
	TransactionState(context.Context, *TransactionStateRequest) (*TransactionStateResponse, error)
	// This returns the node's network identity
	Identify(context.Context, *Empty) (*NodeIdentity, error)
	// Get Base Node network connectivity status
	GetNetworkStatus(context.Context, *Empty) (*NetworkStatusResponse, error)
	// List currently connected peers
	ListConnectedPeers(context.Context, *Empty) (*ListConnectedPeersResponse, error)
	// Get mempool stats
	GetMempoolStats(context.Context, *Empty) (*MempoolStatsResponse, error)
	// Get VNs
	GetActiveValidatorNodes(*GetActiveValidatorNodesRequest, grpc.ServerStreamingServer[GetActiveValidatorNodesResponse]) error
	GetValidatorNodeChanges(context.Context, *GetValidatorNodeChangesRequest) (*GetValidatorNodeChangesResponse, error)
	GetShardKey(context.Context, *GetShardKeyRequest) (*GetShardKeyResponse, error)
	// Get templates
	GetTemplateRegistrations(*GetTemplateRegistrationsRequest, grpc.ServerStreamingServer[GetTemplateRegistrationResponse]) error
	GetSideChainUtxos(*GetSideChainUtxosRequest, grpc.ServerStreamingServer[GetSideChainUtxosResponse]) error
	GetNetworkState(context.Context, *GetNetworkStateRequest) (*GetNetworkStateResponse, error)
	// PayRef (Payment Reference) lookup for block explorers and external services
	SearchPaymentReferences(*SearchPaymentReferencesRequest, grpc.ServerStreamingServer[PaymentReferenceResponse]) error
	// PayRef (Payment Reference) lookup for block explorers and external services via output hash
	SearchPaymentReferencesViaOutputHash(*FetchMatchingUtxosRequest, grpc.ServerStreamingServer[PaymentReferenceResponse]) error
	mustEmbedUnimplementedBaseNodeServer()
}

// UnimplementedBaseNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseNodeServer struct{}

func (UnimplementedBaseNodeServer) ListHeaders(*ListHeadersRequest, grpc.ServerStreamingServer[BlockHeaderResponse]) error {
	return status.Error(codes.Unimplemented, "method ListHeaders not implemented")
}
func (UnimplementedBaseNodeServer) GetHeaderByHash(context.Context, *GetHeaderByHashRequest) (*BlockHeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeaderByHash not implemented")
}
func (UnimplementedBaseNodeServer) GetBlocks(*GetBlocksRequest, grpc.ServerStreamingServer[HistoricalBlock]) error {
	return status.Error(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedBaseNodeServer) GetBlockTiming(context.Context, *HeightRequest) (*BlockTimingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockTiming not implemented")
}
func (UnimplementedBaseNodeServer) GetConstants(context.Context, *BlockHeight) (*ConsensusConstants, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConstants not implemented")
}
func (UnimplementedBaseNodeServer) GetBlockSize(context.Context, *BlockGroupRequest) (*BlockGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockSize not implemented")
}
func (UnimplementedBaseNodeServer) GetBlockFees(context.Context, *BlockGroupRequest) (*BlockGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockFees not implemented")
}
func (UnimplementedBaseNodeServer) GetVersion(context.Context, *Empty) (*BaseNodeGetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedBaseNodeServer) CheckForUpdates(context.Context, *Empty) (*SoftwareUpdate, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckForUpdates not implemented")
}
func (UnimplementedBaseNodeServer) GetTokensInCirculation(*GetBlocksRequest, grpc.ServerStreamingServer[ValueAtHeightResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTokensInCirculation not implemented")
}
func (UnimplementedBaseNodeServer) GetNetworkDifficulty(*HeightRequest, grpc.ServerStreamingServer[NetworkDifficultyResponse]) error {
	return status.Error(codes.Unimplemented, "method GetNetworkDifficulty not implemented")
}
func (UnimplementedBaseNodeServer) GetNewBlockTemplate(context.Context, *NewBlockTemplateRequest) (*NewBlockTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewBlockTemplate not implemented")
}
func (UnimplementedBaseNodeServer) GetNewBlock(context.Context, *NewBlockTemplate) (*GetNewBlockResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewBlock not implemented")
}
func (UnimplementedBaseNodeServer) GetNewBlockWithCoinbases(context.Context, *GetNewBlockWithCoinbasesRequest) (*GetNewBlockResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewBlockWithCoinbases not implemented")
}
func (UnimplementedBaseNodeServer) GetNewBlockTemplateWithCoinbases(context.Context, *GetNewBlockTemplateWithCoinbasesRequest) (*GetNewBlockResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewBlockTemplateWithCoinbases not implemented")
}
func (UnimplementedBaseNodeServer) GetNewBlockBlob(context.Context, *NewBlockTemplate) (*GetNewBlockBlobResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewBlockBlob not implemented")
}
func (UnimplementedBaseNodeServer) SubmitBlock(context.Context, *Block) (*SubmitBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBlock not implemented")
}
func (UnimplementedBaseNodeServer) SubmitBlockBlob(context.Context, *BlockBlobRequest) (*SubmitBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBlockBlob not implemented")
}
func (UnimplementedBaseNodeServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedBaseNodeServer) GetSyncInfo(context.Context, *Empty) (*SyncInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncInfo not implemented")
}
func (UnimplementedBaseNodeServer) GetSyncProgress(context.Context, *Empty) (*SyncProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncProgress not implemented")
}
func (UnimplementedBaseNodeServer) GetTipInfo(context.Context, *Empty) (*TipInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTipInfo not implemented")
}
func (UnimplementedBaseNodeServer) SearchKernels(*SearchKernelsRequest, grpc.ServerStreamingServer[HistoricalBlock]) error {
	return status.Error(codes.Unimplemented, "method SearchKernels not implemented")
}
func (UnimplementedBaseNodeServer) SearchUtxos(*SearchUtxosRequest, grpc.ServerStreamingServer[HistoricalBlock]) error {
	return status.Error(codes.Unimplemented, "method SearchUtxos not implemented")
}
func (UnimplementedBaseNodeServer) FetchMatchingUtxos(*FetchMatchingUtxosRequest, grpc.ServerStreamingServer[FetchMatchingUtxosResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchMatchingUtxos not implemented")
}
func (UnimplementedBaseNodeServer) GetPeers(*GetPeersRequest, grpc.ServerStreamingServer[GetPeersResponse]) error {
	return status.Error(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedBaseNodeServer) GetMempoolTransactions(*GetMempoolTransactionsRequest, grpc.ServerStreamingServer[GetMempoolTransactionsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetMempoolTransactions not implemented")
}
func (UnimplementedBaseNodeServer) TransactionState(context.Context, *TransactionStateRequest) (*TransactionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransactionState not implemented")
}
func (UnimplementedBaseNodeServer) Identify(context.Context, *Empty) (*NodeIdentity, error) {
	return nil, status.Error(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedBaseNodeServer) GetNetworkStatus(context.Context, *Empty) (*NetworkStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkStatus not implemented")
}
func (UnimplementedBaseNodeServer) ListConnectedPeers(context.Context, *Empty) (*ListConnectedPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectedPeers not implemented")
}
func (UnimplementedBaseNodeServer) GetMempoolStats(context.Context, *Empty) (*MempoolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMempoolStats not implemented")
}
func (UnimplementedBaseNodeServer) GetActiveValidatorNodes(*GetActiveValidatorNodesRequest, grpc.ServerStreamingServer[GetActiveValidatorNodesResponse]) error {
	return status.Error(codes.Unimplemented, "method GetActiveValidatorNodes not implemented")
}
func (UnimplementedBaseNodeServer) GetValidatorNodeChanges(context.Context, *GetValidatorNodeChangesRequest) (*GetValidatorNodeChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValidatorNodeChanges not implemented")
}
func (UnimplementedBaseNodeServer) GetShardKey(context.Context, *GetShardKeyRequest) (*GetShardKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardKey not implemented")
}
func (UnimplementedBaseNodeServer) GetTemplateRegistrations(*GetTemplateRegistrationsRequest, grpc.ServerStreamingServer[GetTemplateRegistrationResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTemplateRegistrations not implemented")
}
func (UnimplementedBaseNodeServer) GetSideChainUtxos(*GetSideChainUtxosRequest, grpc.ServerStreamingServer[GetSideChainUtxosResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSideChainUtxos not implemented")
}
func (UnimplementedBaseNodeServer) GetNetworkState(context.Context, *GetNetworkStateRequest) (*GetNetworkStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkState not implemented")
}
func (UnimplementedBaseNodeServer) SearchPaymentReferences(*SearchPaymentReferencesRequest, grpc.ServerStreamingServer[PaymentReferenceResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchPaymentReferences not implemented")
}
func (UnimplementedBaseNodeServer) SearchPaymentReferencesViaOutputHash(*FetchMatchingUtxosRequest, grpc.ServerStreamingServer[PaymentReferenceResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchPaymentReferencesViaOutputHash not implemented")
}
func (UnimplementedBaseNodeServer) mustEmbedUnimplementedBaseNodeServer() {}
func (UnimplementedBaseNodeServer) testEmbeddedByValue()                  {}

// UnsafeBaseNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseNodeServer will
// result in compilation errors.
type UnsafeBaseNodeServer interface {
	mustEmbedUnimplementedBaseNodeServer()
}

func RegisterBaseNodeServer(s grpc.ServiceRegistrar, srv BaseNodeServer) {
	// If the following call panics, it indicates UnimplementedBaseNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseNode_ServiceDesc, srv)
}

func _BaseNode_ListHeaders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListHeadersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).ListHeaders(m, &grpc.GenericServerStream[ListHeadersRequest, BlockHeaderResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_ListHeadersServer = grpc.ServerStreamingServer[BlockHeaderResponse]

func _BaseNode_GetHeaderByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeaderByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetHeaderByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetHeaderByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetHeaderByHash(ctx, req.(*GetHeaderByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetBlocks(m, &grpc.GenericServerStream[GetBlocksRequest, HistoricalBlock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetBlocksServer = grpc.ServerStreamingServer[HistoricalBlock]

func _BaseNode_GetBlockTiming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetBlockTiming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetBlockTiming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetBlockTiming(ctx, req.(*HeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetConstants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockHeight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetConstants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetConstants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetConstants(ctx, req.(*BlockHeight))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetBlockSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetBlockSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetBlockSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetBlockSize(ctx, req.(*BlockGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetBlockFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetBlockFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetBlockFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetBlockFees(ctx, req.(*BlockGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_CheckForUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).CheckForUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_CheckForUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).CheckForUpdates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetTokensInCirculation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetTokensInCirculation(m, &grpc.GenericServerStream[GetBlocksRequest, ValueAtHeightResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetTokensInCirculationServer = grpc.ServerStreamingServer[ValueAtHeightResponse]

func _BaseNode_GetNetworkDifficulty_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeightRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetNetworkDifficulty(m, &grpc.GenericServerStream[HeightRequest, NetworkDifficultyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetNetworkDifficultyServer = grpc.ServerStreamingServer[NetworkDifficultyResponse]

func _BaseNode_GetNewBlockTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBlockTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNewBlockTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNewBlockTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNewBlockTemplate(ctx, req.(*NewBlockTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetNewBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBlockTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNewBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNewBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNewBlock(ctx, req.(*NewBlockTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetNewBlockWithCoinbases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewBlockWithCoinbasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNewBlockWithCoinbases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNewBlockWithCoinbases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNewBlockWithCoinbases(ctx, req.(*GetNewBlockWithCoinbasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetNewBlockTemplateWithCoinbases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewBlockTemplateWithCoinbasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNewBlockTemplateWithCoinbases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNewBlockTemplateWithCoinbases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNewBlockTemplateWithCoinbases(ctx, req.(*GetNewBlockTemplateWithCoinbasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetNewBlockBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBlockTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNewBlockBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNewBlockBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNewBlockBlob(ctx, req.(*NewBlockTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_SubmitBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).SubmitBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_SubmitBlockBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).SubmitBlockBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_SubmitBlockBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).SubmitBlockBlob(ctx, req.(*BlockBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetSyncInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetSyncInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetSyncInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetSyncInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetSyncProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetSyncProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetSyncProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetSyncProgress(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetTipInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetTipInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetTipInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetTipInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_SearchKernels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchKernelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).SearchKernels(m, &grpc.GenericServerStream[SearchKernelsRequest, HistoricalBlock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchKernelsServer = grpc.ServerStreamingServer[HistoricalBlock]

func _BaseNode_SearchUtxos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchUtxosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).SearchUtxos(m, &grpc.GenericServerStream[SearchUtxosRequest, HistoricalBlock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchUtxosServer = grpc.ServerStreamingServer[HistoricalBlock]

func _BaseNode_FetchMatchingUtxos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchMatchingUtxosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).FetchMatchingUtxos(m, &grpc.GenericServerStream[FetchMatchingUtxosRequest, FetchMatchingUtxosResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_FetchMatchingUtxosServer = grpc.ServerStreamingServer[FetchMatchingUtxosResponse]

func _BaseNode_GetPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPeersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetPeers(m, &grpc.GenericServerStream[GetPeersRequest, GetPeersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetPeersServer = grpc.ServerStreamingServer[GetPeersResponse]

func _BaseNode_GetMempoolTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMempoolTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetMempoolTransactions(m, &grpc.GenericServerStream[GetMempoolTransactionsRequest, GetMempoolTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetMempoolTransactionsServer = grpc.ServerStreamingServer[GetMempoolTransactionsResponse]

func _BaseNode_TransactionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).TransactionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_TransactionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).TransactionState(ctx, req.(*TransactionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).Identify(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetNetworkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNetworkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNetworkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNetworkStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_ListConnectedPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).ListConnectedPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_ListConnectedPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).ListConnectedPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetMempoolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetMempoolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetMempoolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetMempoolStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetActiveValidatorNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActiveValidatorNodesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetActiveValidatorNodes(m, &grpc.GenericServerStream[GetActiveValidatorNodesRequest, GetActiveValidatorNodesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetActiveValidatorNodesServer = grpc.ServerStreamingServer[GetActiveValidatorNodesResponse]

func _BaseNode_GetValidatorNodeChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorNodeChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetValidatorNodeChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetValidatorNodeChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetValidatorNodeChanges(ctx, req.(*GetValidatorNodeChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetShardKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetShardKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetShardKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetShardKey(ctx, req.(*GetShardKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_GetTemplateRegistrations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTemplateRegistrationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetTemplateRegistrations(m, &grpc.GenericServerStream[GetTemplateRegistrationsRequest, GetTemplateRegistrationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetTemplateRegistrationsServer = grpc.ServerStreamingServer[GetTemplateRegistrationResponse]

func _BaseNode_GetSideChainUtxos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSideChainUtxosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).GetSideChainUtxos(m, &grpc.GenericServerStream[GetSideChainUtxosRequest, GetSideChainUtxosResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_GetSideChainUtxosServer = grpc.ServerStreamingServer[GetSideChainUtxosResponse]

func _BaseNode_GetNetworkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseNodeServer).GetNetworkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseNode_GetNetworkState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseNodeServer).GetNetworkState(ctx, req.(*GetNetworkStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseNode_SearchPaymentReferences_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchPaymentReferencesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).SearchPaymentReferences(m, &grpc.GenericServerStream[SearchPaymentReferencesRequest, PaymentReferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchPaymentReferencesServer = grpc.ServerStreamingServer[PaymentReferenceResponse]

func _BaseNode_SearchPaymentReferencesViaOutputHash_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchMatchingUtxosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseNodeServer).SearchPaymentReferencesViaOutputHash(m, &grpc.GenericServerStream[FetchMatchingUtxosRequest, PaymentReferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BaseNode_SearchPaymentReferencesViaOutputHashServer = grpc.ServerStreamingServer[PaymentReferenceResponse]

// BaseNode_ServiceDesc is the grpc.ServiceDesc for BaseNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tari.rpc.BaseNode",
	HandlerType: (*BaseNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHeaderByHash",
			Handler:    _BaseNode_GetHeaderByHash_Handler,
		},
		{
			MethodName: "GetBlockTiming",
			Handler:    _BaseNode_GetBlockTiming_Handler,
		},
		{
			MethodName: "GetConstants",
			Handler:    _BaseNode_GetConstants_Handler,
		},
		{
			MethodName: "GetBlockSize",
			Handler:    _BaseNode_GetBlockSize_Handler,
		},
		{
			MethodName: "GetBlockFees",
			Handler:    _BaseNode_GetBlockFees_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _BaseNode_GetVersion_Handler,
		},
		{
			MethodName: "CheckForUpdates",
			Handler:    _BaseNode_CheckForUpdates_Handler,
		},
		{
			MethodName: "GetNewBlockTemplate",
			Handler:    _BaseNode_GetNewBlockTemplate_Handler,
		},
		{
			MethodName: "GetNewBlock",
			Handler:    _BaseNode_GetNewBlock_Handler,
		},
		{
			MethodName: "GetNewBlockWithCoinbases",
			Handler:    _BaseNode_GetNewBlockWithCoinbases_Handler,
		},
		{
			MethodName: "GetNewBlockTemplateWithCoinbases",
			Handler:    _BaseNode_GetNewBlockTemplateWithCoinbases_Handler,
		},
		{
			MethodName: "GetNewBlockBlob",
			Handler:    _BaseNode_GetNewBlockBlob_Handler,
		},
		{
			MethodName: "SubmitBlock",
			Handler:    _BaseNode_SubmitBlock_Handler,
		},
		{
			MethodName: "SubmitBlockBlob",
			Handler:    _BaseNode_SubmitBlockBlob_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _BaseNode_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetSyncInfo",
			Handler:    _BaseNode_GetSyncInfo_Handler,
		},
		{
			MethodName: "GetSyncProgress",
			Handler:    _BaseNode_GetSyncProgress_Handler,
		},
		{
			MethodName: "GetTipInfo",
			Handler:    _BaseNode_GetTipInfo_Handler,
		},
		{
			MethodName: "TransactionState",
			Handler:    _BaseNode_TransactionState_Handler,
		},
		{
			MethodName: "Identify",
			Handler:    _BaseNode_Identify_Handler,
		},
		{
			MethodName: "GetNetworkStatus",
			Handler:    _BaseNode_GetNetworkStatus_Handler,
		},
		{
			MethodName: "ListConnectedPeers",
			Handler:    _BaseNode_ListConnectedPeers_Handler,
		},
		{
			MethodName: "GetMempoolStats",
			Handler:    _BaseNode_GetMempoolStats_Handler,
		},
		{
			MethodName: "GetValidatorNodeChanges",
			Handler:    _BaseNode_GetValidatorNodeChanges_Handler,
		},
		{
			MethodName: "GetShardKey",
			Handler:    _BaseNode_GetShardKey_Handler,
		},
		{
			MethodName: "GetNetworkState",
			Handler:    _BaseNode_GetNetworkState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListHeaders",
			Handler:       _BaseNode_ListHeaders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBlocks",
			Handler:       _BaseNode_GetBlocks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTokensInCirculation",
			Handler:       _BaseNode_GetTokensInCirculation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNetworkDifficulty",
			Handler:       _BaseNode_GetNetworkDifficulty_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchKernels",
			Handler:       _BaseNode_SearchKernels_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchUtxos",
			Handler:       _BaseNode_SearchUtxos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchMatchingUtxos",
			Handler:       _BaseNode_FetchMatchingUtxos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPeers",
			Handler:       _BaseNode_GetPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMempoolTransactions",
			Handler:       _BaseNode_GetMempoolTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetActiveValidatorNodes",
			Handler:       _BaseNode_GetActiveValidatorNodes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTemplateRegistrations",
			Handler:       _BaseNode_GetTemplateRegistrations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSideChainUtxos",
			Handler:       _BaseNode_GetSideChainUtxos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchPaymentReferences",
			Handler:       _BaseNode_SearchPaymentReferences_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchPaymentReferencesViaOutputHash",
			Handler:       _BaseNode_SearchPaymentReferencesViaOutputHash_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "base_node.proto",
}
