// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tari_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ShaP2PoolClient is the client API for ShaP2Pool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShaP2PoolClient interface {
	GetTipInfo(ctx context.Context, in *GetTipInfoRequest, opts ...grpc.CallOption) (*GetTipInfoResponse, error)
	GetNewBlock(ctx context.Context, in *GetNewBlockRequest, opts ...grpc.CallOption) (*GetNewBlockResponse, error)
	SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error)
}

type shaP2PoolClient struct {
	cc grpc.ClientConnInterface
}

func NewShaP2PoolClient(cc grpc.ClientConnInterface) ShaP2PoolClient {
	return &shaP2PoolClient{cc}
}

func (c *shaP2PoolClient) GetTipInfo(ctx context.Context, in *GetTipInfoRequest, opts ...grpc.CallOption) (*GetTipInfoResponse, error) {
	out := new(GetTipInfoResponse)
	err := c.cc.Invoke(ctx, "/tari.rpc.ShaP2Pool/GetTipInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaP2PoolClient) GetNewBlock(ctx context.Context, in *GetNewBlockRequest, opts ...grpc.CallOption) (*GetNewBlockResponse, error) {
	out := new(GetNewBlockResponse)
	err := c.cc.Invoke(ctx, "/tari.rpc.ShaP2Pool/GetNewBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaP2PoolClient) SubmitBlock(ctx context.Context, in *SubmitBlockRequest, opts ...grpc.CallOption) (*SubmitBlockResponse, error) {
	out := new(SubmitBlockResponse)
	err := c.cc.Invoke(ctx, "/tari.rpc.ShaP2Pool/SubmitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShaP2PoolServer is the server API for ShaP2Pool service.
// All implementations must embed UnimplementedShaP2PoolServer
// for forward compatibility
type ShaP2PoolServer interface {
	GetTipInfo(context.Context, *GetTipInfoRequest) (*GetTipInfoResponse, error)
	GetNewBlock(context.Context, *GetNewBlockRequest) (*GetNewBlockResponse, error)
	SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error)
	mustEmbedUnimplementedShaP2PoolServer()
}

// UnimplementedShaP2PoolServer must be embedded to have forward compatible implementations.
type UnimplementedShaP2PoolServer struct {
}

func (UnimplementedShaP2PoolServer) GetTipInfo(context.Context, *GetTipInfoRequest) (*GetTipInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTipInfo not implemented")
}
func (UnimplementedShaP2PoolServer) GetNewBlock(context.Context, *GetNewBlockRequest) (*GetNewBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewBlock not implemented")
}
func (UnimplementedShaP2PoolServer) SubmitBlock(context.Context, *SubmitBlockRequest) (*SubmitBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBlock not implemented")
}
func (UnimplementedShaP2PoolServer) mustEmbedUnimplementedShaP2PoolServer() {}

// UnsafeShaP2PoolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShaP2PoolServer will
// result in compilation errors.
type UnsafeShaP2PoolServer interface {
	mustEmbedUnimplementedShaP2PoolServer()
}

func RegisterShaP2PoolServer(s *grpc.Server, srv ShaP2PoolServer) {
	s.RegisterService(&_ShaP2Pool_serviceDesc, srv)
}

func _ShaP2Pool_GetTipInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTipInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaP2PoolServer).GetTipInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tari.rpc.ShaP2Pool/GetTipInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaP2PoolServer).GetTipInfo(ctx, req.(*GetTipInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaP2Pool_GetNewBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaP2PoolServer).GetNewBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tari.rpc.ShaP2Pool/GetNewBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaP2PoolServer).GetNewBlock(ctx, req.(*GetNewBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaP2Pool_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaP2PoolServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tari.rpc.ShaP2Pool/SubmitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaP2PoolServer).SubmitBlock(ctx, req.(*SubmitBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShaP2Pool_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tari.rpc.ShaP2Pool",
	HandlerType: (*ShaP2PoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTipInfo",
			Handler:    _ShaP2Pool_GetTipInfo_Handler,
		},
		{
			MethodName: "GetNewBlock",
			Handler:    _ShaP2Pool_GetNewBlock_Handler,
		},
		{
			MethodName: "SubmitBlock",
			Handler:    _ShaP2Pool_SubmitBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2pool.proto",
}
