// Copyright 2020. The Tari Project
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
// following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
// disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
// following disclaimer in the documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
// products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sidechain_types.proto

package tari_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SideChainFeature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Feature:
	//
	//	*SideChainFeature_ValidatorNodeRegistration
	//	*SideChainFeature_TemplateRegistration
	//	*SideChainFeature_ConfidentialOutput
	//	*SideChainFeature_ValidatorNodeExit
	Feature       isSideChainFeature_Feature `protobuf_oneof:"feature"`
	SidechainId   *SideChainId               `protobuf:"bytes,6,opt,name=sidechain_id,json=sidechainId,proto3" json:"sidechain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SideChainFeature) Reset() {
	*x = SideChainFeature{}
	mi := &file_sidechain_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SideChainFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideChainFeature) ProtoMessage() {}

func (x *SideChainFeature) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideChainFeature.ProtoReflect.Descriptor instead.
func (*SideChainFeature) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{0}
}

func (x *SideChainFeature) GetFeature() isSideChainFeature_Feature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *SideChainFeature) GetValidatorNodeRegistration() *ValidatorNodeRegistration {
	if x != nil {
		if x, ok := x.Feature.(*SideChainFeature_ValidatorNodeRegistration); ok {
			return x.ValidatorNodeRegistration
		}
	}
	return nil
}

func (x *SideChainFeature) GetTemplateRegistration() *TemplateRegistration {
	if x != nil {
		if x, ok := x.Feature.(*SideChainFeature_TemplateRegistration); ok {
			return x.TemplateRegistration
		}
	}
	return nil
}

func (x *SideChainFeature) GetConfidentialOutput() *ConfidentialOutputData {
	if x != nil {
		if x, ok := x.Feature.(*SideChainFeature_ConfidentialOutput); ok {
			return x.ConfidentialOutput
		}
	}
	return nil
}

func (x *SideChainFeature) GetValidatorNodeExit() *ValidatorNodeExit {
	if x != nil {
		if x, ok := x.Feature.(*SideChainFeature_ValidatorNodeExit); ok {
			return x.ValidatorNodeExit
		}
	}
	return nil
}

func (x *SideChainFeature) GetSidechainId() *SideChainId {
	if x != nil {
		return x.SidechainId
	}
	return nil
}

type isSideChainFeature_Feature interface {
	isSideChainFeature_Feature()
}

type SideChainFeature_ValidatorNodeRegistration struct {
	ValidatorNodeRegistration *ValidatorNodeRegistration `protobuf:"bytes,1,opt,name=validator_node_registration,json=validatorNodeRegistration,proto3,oneof"`
}

type SideChainFeature_TemplateRegistration struct {
	TemplateRegistration *TemplateRegistration `protobuf:"bytes,2,opt,name=template_registration,json=templateRegistration,proto3,oneof"`
}

type SideChainFeature_ConfidentialOutput struct {
	ConfidentialOutput *ConfidentialOutputData `protobuf:"bytes,3,opt,name=confidential_output,json=confidentialOutput,proto3,oneof"`
}

type SideChainFeature_ValidatorNodeExit struct {
	ValidatorNodeExit *ValidatorNodeExit `protobuf:"bytes,5,opt,name=validator_node_exit,json=validatorNodeExit,proto3,oneof"`
}

func (*SideChainFeature_ValidatorNodeRegistration) isSideChainFeature_Feature() {}

func (*SideChainFeature_TemplateRegistration) isSideChainFeature_Feature() {}

func (*SideChainFeature_ConfidentialOutput) isSideChainFeature_Feature() {}

func (*SideChainFeature_ValidatorNodeExit) isSideChainFeature_Feature() {}

type SideChainId struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublicKey      []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KnowledgeProof *Signature             `protobuf:"bytes,2,opt,name=knowledge_proof,json=knowledgeProof,proto3" json:"knowledge_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SideChainId) Reset() {
	*x = SideChainId{}
	mi := &file_sidechain_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SideChainId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideChainId) ProtoMessage() {}

func (x *SideChainId) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideChainId.ProtoReflect.Descriptor instead.
func (*SideChainId) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{1}
}

func (x *SideChainId) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SideChainId) GetKnowledgeProof() *Signature {
	if x != nil {
		return x.KnowledgeProof
	}
	return nil
}

type ValidatorNodeRegistration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublicKey      []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature      *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ClaimPublicKey []byte                 `protobuf:"bytes,3,opt,name=claim_public_key,json=claimPublicKey,proto3" json:"claim_public_key,omitempty"`
	MaxEpoch       uint64                 `protobuf:"varint,4,opt,name=max_epoch,json=maxEpoch,proto3" json:"max_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidatorNodeRegistration) Reset() {
	*x = ValidatorNodeRegistration{}
	mi := &file_sidechain_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorNodeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorNodeRegistration) ProtoMessage() {}

func (x *ValidatorNodeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorNodeRegistration.ProtoReflect.Descriptor instead.
func (*ValidatorNodeRegistration) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorNodeRegistration) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorNodeRegistration) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ValidatorNodeRegistration) GetClaimPublicKey() []byte {
	if x != nil {
		return x.ClaimPublicKey
	}
	return nil
}

func (x *ValidatorNodeRegistration) GetMaxEpoch() uint64 {
	if x != nil {
		return x.MaxEpoch
	}
	return 0
}

type ValidatorNodeExit struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PublicKey []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	MaxEpoch  uint64                 `protobuf:"varint,3,opt,name=max_epoch,json=maxEpoch,proto3" json:"max_epoch,omitempty"`
	// The activation epoch of the registration being exited (part of the signed message).
	ActivationEpoch uint64 `protobuf:"varint,4,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidatorNodeExit) Reset() {
	*x = ValidatorNodeExit{}
	mi := &file_sidechain_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorNodeExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorNodeExit) ProtoMessage() {}

func (x *ValidatorNodeExit) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorNodeExit.ProtoReflect.Descriptor instead.
func (*ValidatorNodeExit) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatorNodeExit) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorNodeExit) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ValidatorNodeExit) GetMaxEpoch() uint64 {
	if x != nil {
		return x.MaxEpoch
	}
	return 0
}

func (x *ValidatorNodeExit) GetActivationEpoch() uint64 {
	if x != nil {
		return x.ActivationEpoch
	}
	return 0
}

type TemplateRegistration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorPublicKey []byte                 `protobuf:"bytes,1,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	AuthorSignature *Signature             `protobuf:"bytes,2,opt,name=author_signature,json=authorSignature,proto3" json:"author_signature,omitempty"`
	TemplateName    string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateVersion uint32                 `protobuf:"varint,4,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	TemplateType    *TemplateType          `protobuf:"bytes,5,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"`
	BuildInfo       *BuildInfo             `protobuf:"bytes,6,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	BinarySha       []byte                 `protobuf:"bytes,7,opt,name=binary_sha,json=binarySha,proto3" json:"binary_sha,omitempty"`
	BinaryUrl       string                 `protobuf:"bytes,8,opt,name=binary_url,json=binaryUrl,proto3" json:"binary_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemplateRegistration) Reset() {
	*x = TemplateRegistration{}
	mi := &file_sidechain_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRegistration) ProtoMessage() {}

func (x *TemplateRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRegistration.ProtoReflect.Descriptor instead.
func (*TemplateRegistration) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateRegistration) GetAuthorPublicKey() []byte {
	if x != nil {
		return x.AuthorPublicKey
	}
	return nil
}

func (x *TemplateRegistration) GetAuthorSignature() *Signature {
	if x != nil {
		return x.AuthorSignature
	}
	return nil
}

func (x *TemplateRegistration) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *TemplateRegistration) GetTemplateVersion() uint32 {
	if x != nil {
		return x.TemplateVersion
	}
	return 0
}

func (x *TemplateRegistration) GetTemplateType() *TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return nil
}

func (x *TemplateRegistration) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *TemplateRegistration) GetBinarySha() []byte {
	if x != nil {
		return x.BinarySha
	}
	return nil
}

func (x *TemplateRegistration) GetBinaryUrl() string {
	if x != nil {
		return x.BinaryUrl
	}
	return ""
}

type ConfidentialOutputData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClaimPublicKey []byte                 `protobuf:"bytes,1,opt,name=claim_public_key,json=claimPublicKey,proto3" json:"claim_public_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfidentialOutputData) Reset() {
	*x = ConfidentialOutputData{}
	mi := &file_sidechain_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidentialOutputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidentialOutputData) ProtoMessage() {}

func (x *ConfidentialOutputData) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidentialOutputData.ProtoReflect.Descriptor instead.
func (*ConfidentialOutputData) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{5}
}

func (x *ConfidentialOutputData) GetClaimPublicKey() []byte {
	if x != nil {
		return x.ClaimPublicKey
	}
	return nil
}

type TemplateType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TemplateType:
	//
	//	*TemplateType_Wasm
	//	*TemplateType_Flow
	//	*TemplateType_Manifest
	TemplateType  isTemplateType_TemplateType `protobuf_oneof:"template_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateType) Reset() {
	*x = TemplateType{}
	mi := &file_sidechain_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateType) ProtoMessage() {}

func (x *TemplateType) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateType.ProtoReflect.Descriptor instead.
func (*TemplateType) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateType) GetTemplateType() isTemplateType_TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return nil
}

func (x *TemplateType) GetWasm() *WasmInfo {
	if x != nil {
		if x, ok := x.TemplateType.(*TemplateType_Wasm); ok {
			return x.Wasm
		}
	}
	return nil
}

func (x *TemplateType) GetFlow() *FlowInfo {
	if x != nil {
		if x, ok := x.TemplateType.(*TemplateType_Flow); ok {
			return x.Flow
		}
	}
	return nil
}

func (x *TemplateType) GetManifest() *ManifestInfo {
	if x != nil {
		if x, ok := x.TemplateType.(*TemplateType_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

type isTemplateType_TemplateType interface {
	isTemplateType_TemplateType()
}

type TemplateType_Wasm struct {
	Wasm *WasmInfo `protobuf:"bytes,1,opt,name=wasm,proto3,oneof"`
}

type TemplateType_Flow struct {
	Flow *FlowInfo `protobuf:"bytes,2,opt,name=flow,proto3,oneof"`
}

type TemplateType_Manifest struct {
	Manifest *ManifestInfo `protobuf:"bytes,3,opt,name=manifest,proto3,oneof"`
}

func (*TemplateType_Wasm) isTemplateType_TemplateType() {}

func (*TemplateType_Flow) isTemplateType_TemplateType() {}

func (*TemplateType_Manifest) isTemplateType_TemplateType() {}

type WasmInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbiVersion    uint32                 `protobuf:"varint,1,opt,name=abi_version,json=abiVersion,proto3" json:"abi_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmInfo) Reset() {
	*x = WasmInfo{}
	mi := &file_sidechain_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmInfo) ProtoMessage() {}

func (x *WasmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmInfo.ProtoReflect.Descriptor instead.
func (*WasmInfo) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{7}
}

func (x *WasmInfo) GetAbiVersion() uint32 {
	if x != nil {
		return x.AbiVersion
	}
	return 0
}

type FlowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowInfo) Reset() {
	*x = FlowInfo{}
	mi := &file_sidechain_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowInfo) ProtoMessage() {}

func (x *FlowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowInfo.ProtoReflect.Descriptor instead.
func (*FlowInfo) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{8}
}

type ManifestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestInfo) Reset() {
	*x = ManifestInfo{}
	mi := &file_sidechain_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestInfo) ProtoMessage() {}

func (x *ManifestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestInfo.ProtoReflect.Descriptor instead.
func (*ManifestInfo) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{9}
}

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	CommitHash    []byte                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_sidechain_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sidechain_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_sidechain_types_proto_rawDescGZIP(), []int{10}
}

func (x *BuildInfo) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *BuildInfo) GetCommitHash() []byte {
	if x != nil {
		return x.CommitHash
	}
	return nil
}

var File_sidechain_types_proto protoreflect.FileDescriptor

const file_sidechain_types_proto_rawDesc = "" +
	"\n" +
	"\x15sidechain_types.proto\x12\btari.rpc\x1a\vtypes.proto\"\xcf\x03\n" +
	"\x10SideChainFeature\x12e\n" +
	"\x1bvalidator_node_registration\x18\x01 \x01(\v2#.tari.rpc.ValidatorNodeRegistrationH\x00R\x19validatorNodeRegistration\x12U\n" +
	"\x15template_registration\x18\x02 \x01(\v2\x1e.tari.rpc.TemplateRegistrationH\x00R\x14templateRegistration\x12S\n" +
	"\x13confidential_output\x18\x03 \x01(\v2 .tari.rpc.ConfidentialOutputDataH\x00R\x12confidentialOutput\x12M\n" +
	"\x13validator_node_exit\x18\x05 \x01(\v2\x1b.tari.rpc.ValidatorNodeExitH\x00R\x11validatorNodeExit\x128\n" +
	"\fsidechain_id\x18\x06 \x01(\v2\x15.tari.rpc.SideChainIdR\vsidechainIdB\t\n" +
	"\afeatureJ\x04\b\x04\x10\x05R\x0eeviction_proof\"j\n" +
	"\vSideChainId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12<\n" +
	"\x0fknowledge_proof\x18\x02 \x01(\v2\x13.tari.rpc.SignatureR\x0eknowledgeProof\"\xb4\x01\n" +
	"\x19ValidatorNodeRegistration\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x121\n" +
	"\tsignature\x18\x02 \x01(\v2\x13.tari.rpc.SignatureR\tsignature\x12(\n" +
	"\x10claim_public_key\x18\x03 \x01(\fR\x0eclaimPublicKey\x12\x1b\n" +
	"\tmax_epoch\x18\x04 \x01(\x04R\bmaxEpoch\"\xad\x01\n" +
	"\x11ValidatorNodeExit\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x121\n" +
	"\tsignature\x18\x02 \x01(\v2\x13.tari.rpc.SignatureR\tsignature\x12\x1b\n" +
	"\tmax_epoch\x18\x03 \x01(\x04R\bmaxEpoch\x12)\n" +
	"\x10activation_epoch\x18\x04 \x01(\x04R\x0factivationEpoch\"\x81\x03\n" +
	"\x14TemplateRegistration\x12*\n" +
	"\x11author_public_key\x18\x01 \x01(\fR\x0fauthorPublicKey\x12>\n" +
	"\x10author_signature\x18\x02 \x01(\v2\x13.tari.rpc.SignatureR\x0fauthorSignature\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12)\n" +
	"\x10template_version\x18\x04 \x01(\rR\x0ftemplateVersion\x12;\n" +
	"\rtemplate_type\x18\x05 \x01(\v2\x16.tari.rpc.TemplateTypeR\ftemplateType\x122\n" +
	"\n" +
	"build_info\x18\x06 \x01(\v2\x13.tari.rpc.BuildInfoR\tbuildInfo\x12\x1d\n" +
	"\n" +
	"binary_sha\x18\a \x01(\fR\tbinarySha\x12\x1d\n" +
	"\n" +
	"binary_url\x18\b \x01(\tR\tbinaryUrl\"B\n" +
	"\x16ConfidentialOutputData\x12(\n" +
	"\x10claim_public_key\x18\x01 \x01(\fR\x0eclaimPublicKey\"\xa9\x01\n" +
	"\fTemplateType\x12(\n" +
	"\x04wasm\x18\x01 \x01(\v2\x12.tari.rpc.WasmInfoH\x00R\x04wasm\x12(\n" +
	"\x04flow\x18\x02 \x01(\v2\x12.tari.rpc.FlowInfoH\x00R\x04flow\x124\n" +
	"\bmanifest\x18\x03 \x01(\v2\x16.tari.rpc.ManifestInfoH\x00R\bmanifestB\x0f\n" +
	"\rtemplate_type\"+\n" +
	"\bWasmInfo\x12\x1f\n" +
	"\vabi_version\x18\x01 \x01(\rR\n" +
	"abiVersion\"\n" +
	"\n" +
	"\bFlowInfo\"\x0e\n" +
	"\fManifestInfo\"G\n" +
	"\tBuildInfo\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\fR\n" +
	"commitHashB4Z2github.com/Snipa22/go-tari-grpc-lib/tari_generatedb\x06proto3"

var (
	file_sidechain_types_proto_rawDescOnce sync.Once
	file_sidechain_types_proto_rawDescData []byte
)

func file_sidechain_types_proto_rawDescGZIP() []byte {
	file_sidechain_types_proto_rawDescOnce.Do(func() {
		file_sidechain_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidechain_types_proto_rawDesc), len(file_sidechain_types_proto_rawDesc)))
	})
	return file_sidechain_types_proto_rawDescData
}

var file_sidechain_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sidechain_types_proto_goTypes = []any{
	(*SideChainFeature)(nil),          // 0: tari.rpc.SideChainFeature
	(*SideChainId)(nil),               // 1: tari.rpc.SideChainId
	(*ValidatorNodeRegistration)(nil), // 2: tari.rpc.ValidatorNodeRegistration
	(*ValidatorNodeExit)(nil),         // 3: tari.rpc.ValidatorNodeExit
	(*TemplateRegistration)(nil),      // 4: tari.rpc.TemplateRegistration
	(*ConfidentialOutputData)(nil),    // 5: tari.rpc.ConfidentialOutputData
	(*TemplateType)(nil),              // 6: tari.rpc.TemplateType
	(*WasmInfo)(nil),                  // 7: tari.rpc.WasmInfo
	(*FlowInfo)(nil),                  // 8: tari.rpc.FlowInfo
	(*ManifestInfo)(nil),              // 9: tari.rpc.ManifestInfo
	(*BuildInfo)(nil),                 // 10: tari.rpc.BuildInfo
	(*Signature)(nil),                 // 11: tari.rpc.Signature
}
var file_sidechain_types_proto_depIdxs = []int32{
	2,  // 0: tari.rpc.SideChainFeature.validator_node_registration:type_name -> tari.rpc.ValidatorNodeRegistration
	4,  // 1: tari.rpc.SideChainFeature.template_registration:type_name -> tari.rpc.TemplateRegistration
	5,  // 2: tari.rpc.SideChainFeature.confidential_output:type_name -> tari.rpc.ConfidentialOutputData
	3,  // 3: tari.rpc.SideChainFeature.validator_node_exit:type_name -> tari.rpc.ValidatorNodeExit
	1,  // 4: tari.rpc.SideChainFeature.sidechain_id:type_name -> tari.rpc.SideChainId
	11, // 5: tari.rpc.SideChainId.knowledge_proof:type_name -> tari.rpc.Signature
	11, // 6: tari.rpc.ValidatorNodeRegistration.signature:type_name -> tari.rpc.Signature
	11, // 7: tari.rpc.ValidatorNodeExit.signature:type_name -> tari.rpc.Signature
	11, // 8: tari.rpc.TemplateRegistration.author_signature:type_name -> tari.rpc.Signature
	6,  // 9: tari.rpc.TemplateRegistration.template_type:type_name -> tari.rpc.TemplateType
	10, // 10: tari.rpc.TemplateRegistration.build_info:type_name -> tari.rpc.BuildInfo
	7,  // 11: tari.rpc.TemplateType.wasm:type_name -> tari.rpc.WasmInfo
	8,  // 12: tari.rpc.TemplateType.flow:type_name -> tari.rpc.FlowInfo
	9,  // 13: tari.rpc.TemplateType.manifest:type_name -> tari.rpc.ManifestInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sidechain_types_proto_init() }
func file_sidechain_types_proto_init() {
	if File_sidechain_types_proto != nil {
		return
	}
	file_types_proto_init()
	file_sidechain_types_proto_msgTypes[0].OneofWrappers = []any{
		(*SideChainFeature_ValidatorNodeRegistration)(nil),
		(*SideChainFeature_TemplateRegistration)(nil),
		(*SideChainFeature_ConfidentialOutput)(nil),
		(*SideChainFeature_ValidatorNodeExit)(nil),
	}
	file_sidechain_types_proto_msgTypes[6].OneofWrappers = []any{
		(*TemplateType_Wasm)(nil),
		(*TemplateType_Flow)(nil),
		(*TemplateType_Manifest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidechain_types_proto_rawDesc), len(file_sidechain_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sidechain_types_proto_goTypes,
		DependencyIndexes: file_sidechain_types_proto_depIdxs,
		MessageInfos:      file_sidechain_types_proto_msgTypes,
	}.Build()
	File_sidechain_types_proto = out.File
	file_sidechain_types_proto_goTypes = nil
	file_sidechain_types_proto_depIdxs = nil
}
