// Copyright 2020. The Tari Project
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
// following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
// disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
// following disclaimer in the documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
// products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: types.proto

package tari_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Output types
type OutputType int32

const (
	OutputType_STANDARD                    OutputType = 0
	OutputType_COINBASE                    OutputType = 1
	OutputType_BURN                        OutputType = 2
	OutputType_VALIDATOR_NODE_REGISTRATION OutputType = 3
	OutputType_CODE_TEMPLATE_REGISTRATION  OutputType = 4
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "STANDARD",
		1: "COINBASE",
		2: "BURN",
		3: "VALIDATOR_NODE_REGISTRATION",
		4: "CODE_TEMPLATE_REGISTRATION",
	}
	OutputType_value = map[string]int32{
		"STANDARD":                    0,
		"COINBASE":                    1,
		"BURN":                        2,
		"VALIDATOR_NODE_REGISTRATION": 3,
		"CODE_TEMPLATE_REGISTRATION":  4,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

// / Range proof types
type RangeProofType int32

const (
	RangeProofType_BULLETPROOF_PLUS RangeProofType = 0
	RangeProofType_REVEALED_VALUE   RangeProofType = 1
)

// Enum value maps for RangeProofType.
var (
	RangeProofType_name = map[int32]string{
		0: "BULLETPROOF_PLUS",
		1: "REVEALED_VALUE",
	}
	RangeProofType_value = map[string]int32{
		"BULLETPROOF_PLUS": 0,
		"REVEALED_VALUE":   1,
	}
)

func (x RangeProofType) Enum() *RangeProofType {
	p := new(RangeProofType)
	*p = x
	return p
}

func (x RangeProofType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeProofType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (RangeProofType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x RangeProofType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeProofType.Descriptor instead.
func (RangeProofType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

// / An unsigned range interface to more accurately represent Rust native Range's
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           uint64                 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint64                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Range) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Range) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// / An Empty placeholder for endpoints without request parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

// / Define an interface for block height
type BlockHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeight) Reset() {
	*x = BlockHeight{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeight) ProtoMessage() {}

func (x *BlockHeight) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeight.ProtoReflect.Descriptor instead.
func (*BlockHeight) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *BlockHeight) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// Define the explicit Signature implementation for the Minotari base layer. A different signature scheme can be
// employed by redefining this type.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicNonce   []byte                 `protobuf:"bytes,1,opt,name=public_nonce,json=publicNonce,proto3" json:"public_nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetPublicNonce() []byte {
	if x != nil {
		return x.PublicNonce
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Define the explicit ComAndPubSignature implementation for the Minotari base layer. A different signature scheme can be
// employed by redefining this type.
type ComAndPubSignature struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EphemeralCommitment []byte                 `protobuf:"bytes,1,opt,name=ephemeral_commitment,json=ephemeralCommitment,proto3" json:"ephemeral_commitment,omitempty"`
	EphemeralPubkey     []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`
	UA                  []byte                 `protobuf:"bytes,3,opt,name=u_a,json=uA,proto3" json:"u_a,omitempty"`
	UX                  []byte                 `protobuf:"bytes,4,opt,name=u_x,json=uX,proto3" json:"u_x,omitempty"`
	UY                  []byte                 `protobuf:"bytes,5,opt,name=u_y,json=uY,proto3" json:"u_y,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComAndPubSignature) Reset() {
	*x = ComAndPubSignature{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComAndPubSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComAndPubSignature) ProtoMessage() {}

func (x *ComAndPubSignature) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComAndPubSignature.ProtoReflect.Descriptor instead.
func (*ComAndPubSignature) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *ComAndPubSignature) GetEphemeralCommitment() []byte {
	if x != nil {
		return x.EphemeralCommitment
	}
	return nil
}

func (x *ComAndPubSignature) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *ComAndPubSignature) GetUA() []byte {
	if x != nil {
		return x.UA
	}
	return nil
}

func (x *ComAndPubSignature) GetUX() []byte {
	if x != nil {
		return x.UX
	}
	return nil
}

func (x *ComAndPubSignature) GetUY() []byte {
	if x != nil {
		return x.UY
	}
	return nil
}

// Define the explicit CommitmentSignature implementation for the Minotari base layer. A different signature scheme can be
// employed by redefining this type
type CommitmentSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicNonce   []byte                 `protobuf:"bytes,1,opt,name=public_nonce,json=publicNonce,proto3" json:"public_nonce,omitempty"`
	U             []byte                 `protobuf:"bytes,2,opt,name=u,proto3" json:"u,omitempty"`
	V             []byte                 `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentSignature) Reset() {
	*x = CommitmentSignature{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentSignature) ProtoMessage() {}

func (x *CommitmentSignature) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentSignature.ProtoReflect.Descriptor instead.
func (*CommitmentSignature) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *CommitmentSignature) GetPublicNonce() []byte {
	if x != nil {
		return x.PublicNonce
	}
	return nil
}

func (x *CommitmentSignature) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

func (x *CommitmentSignature) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

// / PoW Algorithm constants
type PowAlgorithmConstants struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinDifficulty uint64                 `protobuf:"varint,2,opt,name=min_difficulty,json=minDifficulty,proto3" json:"min_difficulty,omitempty"`
	MaxDifficulty uint64                 `protobuf:"varint,3,opt,name=max_difficulty,json=maxDifficulty,proto3" json:"max_difficulty,omitempty"`
	TargetTime    uint64                 `protobuf:"varint,4,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowAlgorithmConstants) Reset() {
	*x = PowAlgorithmConstants{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowAlgorithmConstants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowAlgorithmConstants) ProtoMessage() {}

func (x *PowAlgorithmConstants) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowAlgorithmConstants.ProtoReflect.Descriptor instead.
func (*PowAlgorithmConstants) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *PowAlgorithmConstants) GetMinDifficulty() uint64 {
	if x != nil {
		return x.MinDifficulty
	}
	return 0
}

func (x *PowAlgorithmConstants) GetMaxDifficulty() uint64 {
	if x != nil {
		return x.MaxDifficulty
	}
	return 0
}

func (x *PowAlgorithmConstants) GetTargetTime() uint64 {
	if x != nil {
		return x.TargetTime
	}
	return 0
}

// / Weight params
type WeightParams struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	KernelWeight                   uint64                 `protobuf:"varint,1,opt,name=kernel_weight,json=kernelWeight,proto3" json:"kernel_weight,omitempty"`
	InputWeight                    uint64                 `protobuf:"varint,2,opt,name=input_weight,json=inputWeight,proto3" json:"input_weight,omitempty"`
	OutputWeight                   uint64                 `protobuf:"varint,3,opt,name=output_weight,json=outputWeight,proto3" json:"output_weight,omitempty"`
	FeaturesAndScriptsBytesPerGram uint64                 `protobuf:"varint,4,opt,name=features_and_scripts_bytes_per_gram,json=featuresAndScriptsBytesPerGram,proto3" json:"features_and_scripts_bytes_per_gram,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *WeightParams) Reset() {
	*x = WeightParams{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightParams) ProtoMessage() {}

func (x *WeightParams) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightParams.ProtoReflect.Descriptor instead.
func (*WeightParams) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *WeightParams) GetKernelWeight() uint64 {
	if x != nil {
		return x.KernelWeight
	}
	return 0
}

func (x *WeightParams) GetInputWeight() uint64 {
	if x != nil {
		return x.InputWeight
	}
	return 0
}

func (x *WeightParams) GetOutputWeight() uint64 {
	if x != nil {
		return x.OutputWeight
	}
	return 0
}

func (x *WeightParams) GetFeaturesAndScriptsBytesPerGram() uint64 {
	if x != nil {
		return x.FeaturesAndScriptsBytesPerGram
	}
	return 0
}

// / Output version
type OutputsVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       *Range                 `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	Features      *Range                 `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputsVersion) Reset() {
	*x = OutputsVersion{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputsVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputsVersion) ProtoMessage() {}

func (x *OutputsVersion) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputsVersion.ProtoReflect.Descriptor instead.
func (*OutputsVersion) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *OutputsVersion) GetOutputs() *Range {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *OutputsVersion) GetFeatures() *Range {
	if x != nil {
		return x.Features
	}
	return nil
}

type PermittedRangeProofs struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutputType      OutputType             `protobuf:"varint,1,opt,name=output_type,json=outputType,proto3,enum=tari.rpc.OutputType" json:"output_type,omitempty"`
	RangeProofTypes []RangeProofType       `protobuf:"varint,2,rep,packed,name=range_proof_types,json=rangeProofTypes,proto3,enum=tari.rpc.RangeProofType" json:"range_proof_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PermittedRangeProofs) Reset() {
	*x = PermittedRangeProofs{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermittedRangeProofs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermittedRangeProofs) ProtoMessage() {}

func (x *PermittedRangeProofs) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermittedRangeProofs.ProtoReflect.Descriptor instead.
func (*PermittedRangeProofs) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *PermittedRangeProofs) GetOutputType() OutputType {
	if x != nil {
		return x.OutputType
	}
	return OutputType_STANDARD
}

func (x *PermittedRangeProofs) GetRangeProofTypes() []RangeProofType {
	if x != nil {
		return x.RangeProofTypes
	}
	return nil
}

// / Range proof
type RangeProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofBytes    []byte                 `protobuf:"bytes,1,opt,name=proof_bytes,json=proofBytes,proto3" json:"proof_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeProof) Reset() {
	*x = RangeProof{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeProof) ProtoMessage() {}

func (x *RangeProof) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeProof.ProtoReflect.Descriptor instead.
func (*RangeProof) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *RangeProof) GetProofBytes() []byte {
	if x != nil {
		return x.ProofBytes
	}
	return nil
}

// / Consensus Constants response
type ConsensusConstants struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CoinbaseMinMaturity       uint64                 `protobuf:"varint,1,opt,name=coinbase_min_maturity,json=coinbaseMinMaturity,proto3" json:"coinbase_min_maturity,omitempty"`
	BlockchainVersion         uint32                 `protobuf:"varint,2,opt,name=blockchain_version,json=blockchainVersion,proto3" json:"blockchain_version,omitempty"`
	FutureTimeLimit           uint64                 `protobuf:"varint,3,opt,name=future_time_limit,json=futureTimeLimit,proto3" json:"future_time_limit,omitempty"`
	DifficultyBlockWindow     uint64                 `protobuf:"varint,5,opt,name=difficulty_block_window,json=difficultyBlockWindow,proto3" json:"difficulty_block_window,omitempty"`
	MaxBlockTransactionWeight uint64                 `protobuf:"varint,7,opt,name=max_block_transaction_weight,json=maxBlockTransactionWeight,proto3" json:"max_block_transaction_weight,omitempty"`
	PowAlgoCount              uint64                 `protobuf:"varint,8,opt,name=pow_algo_count,json=powAlgoCount,proto3" json:"pow_algo_count,omitempty"`
	MedianTimestampCount      uint64                 `protobuf:"varint,9,opt,name=median_timestamp_count,json=medianTimestampCount,proto3" json:"median_timestamp_count,omitempty"`
	EmissionInitial           uint64                 `protobuf:"varint,10,opt,name=emission_initial,json=emissionInitial,proto3" json:"emission_initial,omitempty"`
	EmissionDecay             []uint64               `protobuf:"varint,11,rep,packed,name=emission_decay,json=emissionDecay,proto3" json:"emission_decay,omitempty"`
	// Deprecated: Marked as deprecated in types.proto.
	EmissionTail                                  uint64                            `protobuf:"varint,12,opt,name=emission_tail,json=emissionTail,proto3" json:"emission_tail,omitempty"`
	MinSha3XPowDifficulty                         uint64                            `protobuf:"varint,13,opt,name=min_sha3x_pow_difficulty,json=minSha3xPowDifficulty,proto3" json:"min_sha3x_pow_difficulty,omitempty"`
	BlockWeightInputs                             uint64                            `protobuf:"varint,14,opt,name=block_weight_inputs,json=blockWeightInputs,proto3" json:"block_weight_inputs,omitempty"`
	BlockWeightOutputs                            uint64                            `protobuf:"varint,15,opt,name=block_weight_outputs,json=blockWeightOutputs,proto3" json:"block_weight_outputs,omitempty"`
	BlockWeightKernels                            uint64                            `protobuf:"varint,16,opt,name=block_weight_kernels,json=blockWeightKernels,proto3" json:"block_weight_kernels,omitempty"`
	PreMineValue                                  uint64                            `protobuf:"varint,17,opt,name=pre_mine_value,json=preMineValue,proto3" json:"pre_mine_value,omitempty"`
	MaxScriptByteSize                             uint64                            `protobuf:"varint,18,opt,name=max_script_byte_size,json=maxScriptByteSize,proto3" json:"max_script_byte_size,omitempty"`
	EffectiveFromHeight                           uint64                            `protobuf:"varint,20,opt,name=effective_from_height,json=effectiveFromHeight,proto3" json:"effective_from_height,omitempty"`
	ValidBlockchainVersionRange                   *Range                            `protobuf:"bytes,21,opt,name=valid_blockchain_version_range,json=validBlockchainVersionRange,proto3" json:"valid_blockchain_version_range,omitempty"`
	MaxRandomxSeedHeight                          uint64                            `protobuf:"varint,22,opt,name=max_randomx_seed_height,json=maxRandomxSeedHeight,proto3" json:"max_randomx_seed_height,omitempty"`
	ProofOfWork                                   map[uint32]*PowAlgorithmConstants `protobuf:"bytes,23,rep,name=proof_of_work,json=proofOfWork,proto3" json:"proof_of_work,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TransactionWeight                             *WeightParams                     `protobuf:"bytes,24,opt,name=transaction_weight,json=transactionWeight,proto3" json:"transaction_weight,omitempty"`
	InputVersionRange                             *Range                            `protobuf:"bytes,26,opt,name=input_version_range,json=inputVersionRange,proto3" json:"input_version_range,omitempty"`
	OutputVersionRange                            *OutputsVersion                   `protobuf:"bytes,27,opt,name=output_version_range,json=outputVersionRange,proto3" json:"output_version_range,omitempty"`
	KernelVersionRange                            *Range                            `protobuf:"bytes,28,opt,name=kernel_version_range,json=kernelVersionRange,proto3" json:"kernel_version_range,omitempty"`
	PermittedOutputTypes                          []OutputType                      `protobuf:"varint,29,rep,packed,name=permitted_output_types,json=permittedOutputTypes,proto3,enum=tari.rpc.OutputType" json:"permitted_output_types,omitempty"`
	EpochLength                                   uint64                            `protobuf:"varint,30,opt,name=epoch_length,json=epochLength,proto3" json:"epoch_length,omitempty"`
	ValidatorNodeRegistrationMinDepositAmount     uint64                            `protobuf:"varint,31,opt,name=validator_node_registration_min_deposit_amount,json=validatorNodeRegistrationMinDepositAmount,proto3" json:"validator_node_registration_min_deposit_amount,omitempty"`
	ValidatorNodeRegistrationMinLockHeight        uint64                            `protobuf:"varint,32,opt,name=validator_node_registration_min_lock_height,json=validatorNodeRegistrationMinLockHeight,proto3" json:"validator_node_registration_min_lock_height,omitempty"`
	ValidatorNodeRegistrationShuffleIntervalEpoch uint64                            `protobuf:"varint,33,opt,name=validator_node_registration_shuffle_interval_epoch,json=validatorNodeRegistrationShuffleIntervalEpoch,proto3" json:"validator_node_registration_shuffle_interval_epoch,omitempty"`
	PermittedRangeProofTypes                      []*PermittedRangeProofs           `protobuf:"bytes,34,rep,name=permitted_range_proof_types,json=permittedRangeProofTypes,proto3" json:"permitted_range_proof_types,omitempty"`
	InflationBips                                 uint64                            `protobuf:"varint,35,opt,name=inflation_bips,json=inflationBips,proto3" json:"inflation_bips,omitempty"`
	TailEpochLength                               uint64                            `protobuf:"varint,36,opt,name=tail_epoch_length,json=tailEpochLength,proto3" json:"tail_epoch_length,omitempty"`
	MaxBlockCoinbaseCount                         uint64                            `protobuf:"varint,37,opt,name=max_block_coinbase_count,json=maxBlockCoinbaseCount,proto3" json:"max_block_coinbase_count,omitempty"`
	VnRegistrationMaxVnsInitialEpoch              uint32                            `protobuf:"varint,38,opt,name=vn_registration_max_vns_initial_epoch,json=vnRegistrationMaxVnsInitialEpoch,proto3" json:"vn_registration_max_vns_initial_epoch,omitempty"`
	VnRegistrationMaxVnsPerEpoch                  uint32                            `protobuf:"varint,39,opt,name=vn_registration_max_vns_per_epoch,json=vnRegistrationMaxVnsPerEpoch,proto3" json:"vn_registration_max_vns_per_epoch,omitempty"`
	unknownFields                                 protoimpl.UnknownFields
	sizeCache                                     protoimpl.SizeCache
}

func (x *ConsensusConstants) Reset() {
	*x = ConsensusConstants{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusConstants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusConstants) ProtoMessage() {}

func (x *ConsensusConstants) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusConstants.ProtoReflect.Descriptor instead.
func (*ConsensusConstants) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *ConsensusConstants) GetCoinbaseMinMaturity() uint64 {
	if x != nil {
		return x.CoinbaseMinMaturity
	}
	return 0
}

func (x *ConsensusConstants) GetBlockchainVersion() uint32 {
	if x != nil {
		return x.BlockchainVersion
	}
	return 0
}

func (x *ConsensusConstants) GetFutureTimeLimit() uint64 {
	if x != nil {
		return x.FutureTimeLimit
	}
	return 0
}

func (x *ConsensusConstants) GetDifficultyBlockWindow() uint64 {
	if x != nil {
		return x.DifficultyBlockWindow
	}
	return 0
}

func (x *ConsensusConstants) GetMaxBlockTransactionWeight() uint64 {
	if x != nil {
		return x.MaxBlockTransactionWeight
	}
	return 0
}

func (x *ConsensusConstants) GetPowAlgoCount() uint64 {
	if x != nil {
		return x.PowAlgoCount
	}
	return 0
}

func (x *ConsensusConstants) GetMedianTimestampCount() uint64 {
	if x != nil {
		return x.MedianTimestampCount
	}
	return 0
}

func (x *ConsensusConstants) GetEmissionInitial() uint64 {
	if x != nil {
		return x.EmissionInitial
	}
	return 0
}

func (x *ConsensusConstants) GetEmissionDecay() []uint64 {
	if x != nil {
		return x.EmissionDecay
	}
	return nil
}

// Deprecated: Marked as deprecated in types.proto.
func (x *ConsensusConstants) GetEmissionTail() uint64 {
	if x != nil {
		return x.EmissionTail
	}
	return 0
}

func (x *ConsensusConstants) GetMinSha3XPowDifficulty() uint64 {
	if x != nil {
		return x.MinSha3XPowDifficulty
	}
	return 0
}

func (x *ConsensusConstants) GetBlockWeightInputs() uint64 {
	if x != nil {
		return x.BlockWeightInputs
	}
	return 0
}

func (x *ConsensusConstants) GetBlockWeightOutputs() uint64 {
	if x != nil {
		return x.BlockWeightOutputs
	}
	return 0
}

func (x *ConsensusConstants) GetBlockWeightKernels() uint64 {
	if x != nil {
		return x.BlockWeightKernels
	}
	return 0
}

func (x *ConsensusConstants) GetPreMineValue() uint64 {
	if x != nil {
		return x.PreMineValue
	}
	return 0
}

func (x *ConsensusConstants) GetMaxScriptByteSize() uint64 {
	if x != nil {
		return x.MaxScriptByteSize
	}
	return 0
}

func (x *ConsensusConstants) GetEffectiveFromHeight() uint64 {
	if x != nil {
		return x.EffectiveFromHeight
	}
	return 0
}

func (x *ConsensusConstants) GetValidBlockchainVersionRange() *Range {
	if x != nil {
		return x.ValidBlockchainVersionRange
	}
	return nil
}

func (x *ConsensusConstants) GetMaxRandomxSeedHeight() uint64 {
	if x != nil {
		return x.MaxRandomxSeedHeight
	}
	return 0
}

func (x *ConsensusConstants) GetProofOfWork() map[uint32]*PowAlgorithmConstants {
	if x != nil {
		return x.ProofOfWork
	}
	return nil
}

func (x *ConsensusConstants) GetTransactionWeight() *WeightParams {
	if x != nil {
		return x.TransactionWeight
	}
	return nil
}

func (x *ConsensusConstants) GetInputVersionRange() *Range {
	if x != nil {
		return x.InputVersionRange
	}
	return nil
}

func (x *ConsensusConstants) GetOutputVersionRange() *OutputsVersion {
	if x != nil {
		return x.OutputVersionRange
	}
	return nil
}

func (x *ConsensusConstants) GetKernelVersionRange() *Range {
	if x != nil {
		return x.KernelVersionRange
	}
	return nil
}

func (x *ConsensusConstants) GetPermittedOutputTypes() []OutputType {
	if x != nil {
		return x.PermittedOutputTypes
	}
	return nil
}

func (x *ConsensusConstants) GetEpochLength() uint64 {
	if x != nil {
		return x.EpochLength
	}
	return 0
}

func (x *ConsensusConstants) GetValidatorNodeRegistrationMinDepositAmount() uint64 {
	if x != nil {
		return x.ValidatorNodeRegistrationMinDepositAmount
	}
	return 0
}

func (x *ConsensusConstants) GetValidatorNodeRegistrationMinLockHeight() uint64 {
	if x != nil {
		return x.ValidatorNodeRegistrationMinLockHeight
	}
	return 0
}

func (x *ConsensusConstants) GetValidatorNodeRegistrationShuffleIntervalEpoch() uint64 {
	if x != nil {
		return x.ValidatorNodeRegistrationShuffleIntervalEpoch
	}
	return 0
}

func (x *ConsensusConstants) GetPermittedRangeProofTypes() []*PermittedRangeProofs {
	if x != nil {
		return x.PermittedRangeProofTypes
	}
	return nil
}

func (x *ConsensusConstants) GetInflationBips() uint64 {
	if x != nil {
		return x.InflationBips
	}
	return 0
}

func (x *ConsensusConstants) GetTailEpochLength() uint64 {
	if x != nil {
		return x.TailEpochLength
	}
	return 0
}

func (x *ConsensusConstants) GetMaxBlockCoinbaseCount() uint64 {
	if x != nil {
		return x.MaxBlockCoinbaseCount
	}
	return 0
}

func (x *ConsensusConstants) GetVnRegistrationMaxVnsInitialEpoch() uint32 {
	if x != nil {
		return x.VnRegistrationMaxVnsInitialEpoch
	}
	return 0
}

func (x *ConsensusConstants) GetVnRegistrationMaxVnsPerEpoch() uint32 {
	if x != nil {
		return x.VnRegistrationMaxVnsPerEpoch
	}
	return 0
}

// Unsigned decimal value, examples:
//
//	12345.6789 -> { units = 12345, nanos = 678900000 }
//	12345.0006789 -> { units = 12345, nanos = 678900 }
type UDecimalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whole units part of the amount
	Units uint64 `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	// Nano units of the amount (10^-9)
	Nanos         uint32 `protobuf:"fixed32,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDecimalValue) Reset() {
	*x = UDecimalValue{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDecimalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDecimalValue) ProtoMessage() {}

func (x *UDecimalValue) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDecimalValue.ProtoReflect.Descriptor instead.
func (*UDecimalValue) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *UDecimalValue) GetUnits() uint64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *UDecimalValue) GetNanos() uint32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\btari.rpc\"+\n" +
	"\x05Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x04R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x04R\x03max\"\a\n" +
	"\x05Empty\"0\n" +
	"\vBlockHeight\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\"L\n" +
	"\tSignature\x12!\n" +
	"\fpublic_nonce\x18\x01 \x01(\fR\vpublicNonce\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xa5\x01\n" +
	"\x12ComAndPubSignature\x121\n" +
	"\x14ephemeral_commitment\x18\x01 \x01(\fR\x13ephemeralCommitment\x12)\n" +
	"\x10ephemeral_pubkey\x18\x02 \x01(\fR\x0fephemeralPubkey\x12\x0f\n" +
	"\x03u_a\x18\x03 \x01(\fR\x02uA\x12\x0f\n" +
	"\x03u_x\x18\x04 \x01(\fR\x02uX\x12\x0f\n" +
	"\x03u_y\x18\x05 \x01(\fR\x02uY\"T\n" +
	"\x13CommitmentSignature\x12!\n" +
	"\fpublic_nonce\x18\x01 \x01(\fR\vpublicNonce\x12\f\n" +
	"\x01u\x18\x02 \x01(\fR\x01u\x12\f\n" +
	"\x01v\x18\x03 \x01(\fR\x01v\"\x86\x01\n" +
	"\x15PowAlgorithmConstants\x12%\n" +
	"\x0emin_difficulty\x18\x02 \x01(\x04R\rminDifficulty\x12%\n" +
	"\x0emax_difficulty\x18\x03 \x01(\x04R\rmaxDifficulty\x12\x1f\n" +
	"\vtarget_time\x18\x04 \x01(\x04R\n" +
	"targetTime\"\xc8\x01\n" +
	"\fWeightParams\x12#\n" +
	"\rkernel_weight\x18\x01 \x01(\x04R\fkernelWeight\x12!\n" +
	"\finput_weight\x18\x02 \x01(\x04R\vinputWeight\x12#\n" +
	"\routput_weight\x18\x03 \x01(\x04R\foutputWeight\x12K\n" +
	"#features_and_scripts_bytes_per_gram\x18\x04 \x01(\x04R\x1efeaturesAndScriptsBytesPerGram\"h\n" +
	"\x0eOutputsVersion\x12)\n" +
	"\aoutputs\x18\x01 \x01(\v2\x0f.tari.rpc.RangeR\aoutputs\x12+\n" +
	"\bfeatures\x18\x02 \x01(\v2\x0f.tari.rpc.RangeR\bfeatures\"\x93\x01\n" +
	"\x14PermittedRangeProofs\x125\n" +
	"\voutput_type\x18\x01 \x01(\x0e2\x14.tari.rpc.OutputTypeR\n" +
	"outputType\x12D\n" +
	"\x11range_proof_types\x18\x02 \x03(\x0e2\x18.tari.rpc.RangeProofTypeR\x0frangeProofTypes\"-\n" +
	"\n" +
	"RangeProof\x12\x1f\n" +
	"\vproof_bytes\x18\x01 \x01(\fR\n" +
	"proofBytes\"\xc2\x11\n" +
	"\x12ConsensusConstants\x122\n" +
	"\x15coinbase_min_maturity\x18\x01 \x01(\x04R\x13coinbaseMinMaturity\x12-\n" +
	"\x12blockchain_version\x18\x02 \x01(\rR\x11blockchainVersion\x12*\n" +
	"\x11future_time_limit\x18\x03 \x01(\x04R\x0ffutureTimeLimit\x126\n" +
	"\x17difficulty_block_window\x18\x05 \x01(\x04R\x15difficultyBlockWindow\x12?\n" +
	"\x1cmax_block_transaction_weight\x18\a \x01(\x04R\x19maxBlockTransactionWeight\x12$\n" +
	"\x0epow_algo_count\x18\b \x01(\x04R\fpowAlgoCount\x124\n" +
	"\x16median_timestamp_count\x18\t \x01(\x04R\x14medianTimestampCount\x12)\n" +
	"\x10emission_initial\x18\n" +
	" \x01(\x04R\x0femissionInitial\x12%\n" +
	"\x0eemission_decay\x18\v \x03(\x04R\remissionDecay\x12'\n" +
	"\remission_tail\x18\f \x01(\x04B\x02\x18\x01R\femissionTail\x127\n" +
	"\x18min_sha3x_pow_difficulty\x18\r \x01(\x04R\x15minSha3xPowDifficulty\x12.\n" +
	"\x13block_weight_inputs\x18\x0e \x01(\x04R\x11blockWeightInputs\x120\n" +
	"\x14block_weight_outputs\x18\x0f \x01(\x04R\x12blockWeightOutputs\x120\n" +
	"\x14block_weight_kernels\x18\x10 \x01(\x04R\x12blockWeightKernels\x12$\n" +
	"\x0epre_mine_value\x18\x11 \x01(\x04R\fpreMineValue\x12/\n" +
	"\x14max_script_byte_size\x18\x12 \x01(\x04R\x11maxScriptByteSize\x122\n" +
	"\x15effective_from_height\x18\x14 \x01(\x04R\x13effectiveFromHeight\x12T\n" +
	"\x1evalid_blockchain_version_range\x18\x15 \x01(\v2\x0f.tari.rpc.RangeR\x1bvalidBlockchainVersionRange\x125\n" +
	"\x17max_randomx_seed_height\x18\x16 \x01(\x04R\x14maxRandomxSeedHeight\x12Q\n" +
	"\rproof_of_work\x18\x17 \x03(\v2-.tari.rpc.ConsensusConstants.ProofOfWorkEntryR\vproofOfWork\x12E\n" +
	"\x12transaction_weight\x18\x18 \x01(\v2\x16.tari.rpc.WeightParamsR\x11transactionWeight\x12?\n" +
	"\x13input_version_range\x18\x1a \x01(\v2\x0f.tari.rpc.RangeR\x11inputVersionRange\x12J\n" +
	"\x14output_version_range\x18\x1b \x01(\v2\x18.tari.rpc.OutputsVersionR\x12outputVersionRange\x12A\n" +
	"\x14kernel_version_range\x18\x1c \x01(\v2\x0f.tari.rpc.RangeR\x12kernelVersionRange\x12J\n" +
	"\x16permitted_output_types\x18\x1d \x03(\x0e2\x14.tari.rpc.OutputTypeR\x14permittedOutputTypes\x12!\n" +
	"\fepoch_length\x18\x1e \x01(\x04R\vepochLength\x12a\n" +
	".validator_node_registration_min_deposit_amount\x18\x1f \x01(\x04R)validatorNodeRegistrationMinDepositAmount\x12[\n" +
	"+validator_node_registration_min_lock_height\x18  \x01(\x04R&validatorNodeRegistrationMinLockHeight\x12i\n" +
	"2validator_node_registration_shuffle_interval_epoch\x18! \x01(\x04R-validatorNodeRegistrationShuffleIntervalEpoch\x12]\n" +
	"\x1bpermitted_range_proof_types\x18\" \x03(\v2\x1e.tari.rpc.PermittedRangeProofsR\x18permittedRangeProofTypes\x12%\n" +
	"\x0einflation_bips\x18# \x01(\x04R\rinflationBips\x12*\n" +
	"\x11tail_epoch_length\x18$ \x01(\x04R\x0ftailEpochLength\x127\n" +
	"\x18max_block_coinbase_count\x18% \x01(\x04R\x15maxBlockCoinbaseCount\x12O\n" +
	"%vn_registration_max_vns_initial_epoch\x18& \x01(\rR vnRegistrationMaxVnsInitialEpoch\x12G\n" +
	"!vn_registration_max_vns_per_epoch\x18' \x01(\rR\x1cvnRegistrationMaxVnsPerEpoch\x1a_\n" +
	"\x10ProofOfWorkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.tari.rpc.PowAlgorithmConstantsR\x05value:\x028\x01\";\n" +
	"\rUDecimalValue\x12\x14\n" +
	"\x05units\x18\x01 \x01(\x04R\x05units\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\aR\x05nanos*s\n" +
	"\n" +
	"OutputType\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\f\n" +
	"\bCOINBASE\x10\x01\x12\b\n" +
	"\x04BURN\x10\x02\x12\x1f\n" +
	"\x1bVALIDATOR_NODE_REGISTRATION\x10\x03\x12\x1e\n" +
	"\x1aCODE_TEMPLATE_REGISTRATION\x10\x04*:\n" +
	"\x0eRangeProofType\x12\x14\n" +
	"\x10BULLETPROOF_PLUS\x10\x00\x12\x12\n" +
	"\x0eREVEALED_VALUE\x10\x01B4Z2github.com/Snipa22/go-tari-grpc-lib/tari_generatedb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_types_proto_goTypes = []any{
	(OutputType)(0),               // 0: tari.rpc.OutputType
	(RangeProofType)(0),           // 1: tari.rpc.RangeProofType
	(*Range)(nil),                 // 2: tari.rpc.Range
	(*Empty)(nil),                 // 3: tari.rpc.Empty
	(*BlockHeight)(nil),           // 4: tari.rpc.BlockHeight
	(*Signature)(nil),             // 5: tari.rpc.Signature
	(*ComAndPubSignature)(nil),    // 6: tari.rpc.ComAndPubSignature
	(*CommitmentSignature)(nil),   // 7: tari.rpc.CommitmentSignature
	(*PowAlgorithmConstants)(nil), // 8: tari.rpc.PowAlgorithmConstants
	(*WeightParams)(nil),          // 9: tari.rpc.WeightParams
	(*OutputsVersion)(nil),        // 10: tari.rpc.OutputsVersion
	(*PermittedRangeProofs)(nil),  // 11: tari.rpc.PermittedRangeProofs
	(*RangeProof)(nil),            // 12: tari.rpc.RangeProof
	(*ConsensusConstants)(nil),    // 13: tari.rpc.ConsensusConstants
	(*UDecimalValue)(nil),         // 14: tari.rpc.UDecimalValue
	nil,                           // 15: tari.rpc.ConsensusConstants.ProofOfWorkEntry
}
var file_types_proto_depIdxs = []int32{
	2,  // 0: tari.rpc.OutputsVersion.outputs:type_name -> tari.rpc.Range
	2,  // 1: tari.rpc.OutputsVersion.features:type_name -> tari.rpc.Range
	0,  // 2: tari.rpc.PermittedRangeProofs.output_type:type_name -> tari.rpc.OutputType
	1,  // 3: tari.rpc.PermittedRangeProofs.range_proof_types:type_name -> tari.rpc.RangeProofType
	2,  // 4: tari.rpc.ConsensusConstants.valid_blockchain_version_range:type_name -> tari.rpc.Range
	15, // 5: tari.rpc.ConsensusConstants.proof_of_work:type_name -> tari.rpc.ConsensusConstants.ProofOfWorkEntry
	9,  // 6: tari.rpc.ConsensusConstants.transaction_weight:type_name -> tari.rpc.WeightParams
	2,  // 7: tari.rpc.ConsensusConstants.input_version_range:type_name -> tari.rpc.Range
	10, // 8: tari.rpc.ConsensusConstants.output_version_range:type_name -> tari.rpc.OutputsVersion
	2,  // 9: tari.rpc.ConsensusConstants.kernel_version_range:type_name -> tari.rpc.Range
	0,  // 10: tari.rpc.ConsensusConstants.permitted_output_types:type_name -> tari.rpc.OutputType
	11, // 11: tari.rpc.ConsensusConstants.permitted_range_proof_types:type_name -> tari.rpc.PermittedRangeProofs
	8,  // 12: tari.rpc.ConsensusConstants.ProofOfWorkEntry.value:type_name -> tari.rpc.PowAlgorithmConstants
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
